media:
  input: public/static/images
  output: static/images
content:
  - name: posts
    label: Posts
    type: collection
    path: data/blog
    fields:
      - {name: title, label: Title, type: string}
      - {name: date, label: Date, type: date}
      - {name: tags, label: Tags, type: string, list: true}
      - {name: draft, label: Draft, type: boolean, default: true}
      - {name: summary, label: TL;DR, type: string}
      - {name: body, label: Body, type: rich-text }
  - name: projects
    label: Projects
    type: collection
    path: data/projects
    fields:
      - {name: title, label: Title, type: string}
      - {name: date, label: Date, type: date}
      - {name: tags, label: Tags, type: string, list: true}
      - {name: authors, label: Authors, type: string, list: true}
      - {name: draft, label: Draft, type: boolean, default: true}
      - {name: summary, label: TL;DR, type: string}
      - {name: featureImage, label: Feature Image, type: image}
      - {name: body, label: Body, type: rich-text }

  